language: cpp
compiler:
  - g++

git:
  depth: 50
  
sudo: required

before_install:
  - echo "yes" | sudo add-apt-repository ppa:boost-latest/ppa
  - echo "yes" | sudo add-apt-repository ppa:ubuntu-toolchain-r/test
  - sudo apt-get -qq update
  - sudo apt-get install gcc-4.9 g++-4.9 make cmake build-essential openssl libtool patch
  - sudo apt-get install libssl-dev  libreadline-dev zlib1g-dev libbz2-dev libbz2-1.0 git
  - sudo apt-get install libmysqlclient-dev libmysql++-dev
  - sudo apt-get install libboost1.55-dev libboost-thread1.55-dev libboost-system1.55-dev libboost-filesystem1.55-dev libboost-program-options1.55-dev libboost-regex1.55-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
  - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
  
install:
  - mkdir bin
  - cd bin
  - cmake ../ -DCMAKE_INSTALL_PREFIX="/home/travis"

script:
  - make -j 10
